# Generated by Django 2.2.5 on 2020-04-15 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20200415_0909'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DownloadLink',
        ),
    ]
